# Rest-client stöder .env
#@API_URL = {{$dotenv PRODUCTION_API}}
@API_URL = http://localhost:4000

@DEV_TOKEN = {{$dotenv DEV_TOKEN}} 

GET {{API_URL}}/notes
Authorization: Bearer {{DEV_TOKEN}}

### GET single note
GET {{API_URL}}/notes/3
Authorization: Bearer {{DEV_TOKEN}}

### Skapa ny note
POST {{API_URL}}/notes
Content-Type: application/json
Authorization: Bearer {{DEV_TOKEN}}

{
    "note": "någon annans note",
    "board_id": 1
}

### Uppdatera note
PUT {{API_URL}}/notes/1
Content-Type: application/json
Authorization: Bearer {{DEV_TOKEN}}

{
    "note": "Ny text!!"
}

### Uppdatera note
DELETE {{API_URL}}/notes/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZjEyOGJiMy05MTExLTQ0ZTEtOWUyYS0xOTRkMjcyZDhhZjEiLCJuYW1lIjoicmF0YXIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc5MDA5MjcyOCwiZXhwIjoxNzkyNjg0NzI4fQ.90UdkQIKcvUyhC6kWAAkE6hTtyz70pRYPNtrhai5SGs
